"""Initial schema

Revision ID: c001108a6d8e
Revises: 
Create Date: 2026-01-28 20:50:37.913768

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c001108a6d8e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plant_varieties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('common_name', sa.String(length=100), nullable=False),
    sa.Column('scientific_name', sa.String(length=100), nullable=True),
    sa.Column('variety_name', sa.String(length=100), nullable=True),
    sa.Column('days_to_germination_min', sa.Integer(), nullable=True),
    sa.Column('days_to_germination_max', sa.Integer(), nullable=True),
    sa.Column('days_to_harvest', sa.Integer(), nullable=True),
    sa.Column('spacing_inches', sa.Integer(), nullable=True),
    sa.Column('row_spacing_inches', sa.Integer(), nullable=True),
    sa.Column('sun_requirement', sa.Enum('full_sun', 'partial_sun', 'partial_shade', 'full_shade', name='sunrequirement'), nullable=True),
    sa.Column('water_requirement', sa.Enum('low', 'medium', 'high', name='waterrequirement'), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('growing_notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plant_varieties_common_name'), 'plant_varieties', ['common_name'], unique=False)
    op.create_index(op.f('ix_plant_varieties_id'), 'plant_varieties', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('zip_code', sa.String(length=10), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('usda_zone', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('gardens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gardens_id'), 'gardens', ['id'], unique=False)
    op.create_table('seed_batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('plant_variety_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=200), nullable=True),
    sa.Column('harvest_year', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['plant_variety_id'], ['plant_varieties.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_seed_batches_id'), 'seed_batches', ['id'], unique=False)
    op.create_table('germination_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('seed_batch_id', sa.Integer(), nullable=False),
    sa.Column('plant_variety_id', sa.Integer(), nullable=False),
    sa.Column('started_date', sa.Date(), nullable=False),
    sa.Column('germination_location', sa.String(length=100), nullable=True),
    sa.Column('seed_count', sa.Integer(), nullable=True),
    sa.Column('germinated', sa.Boolean(), nullable=True),
    sa.Column('germination_date', sa.Date(), nullable=True),
    sa.Column('germination_count', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['plant_variety_id'], ['plant_varieties.id'], ),
    sa.ForeignKeyConstraint(['seed_batch_id'], ['seed_batches.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_germination_events_id'), 'germination_events', ['id'], unique=False)
    op.create_table('planting_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('garden_id', sa.Integer(), nullable=False),
    sa.Column('plant_variety_id', sa.Integer(), nullable=False),
    sa.Column('germination_event_id', sa.Integer(), nullable=True),
    sa.Column('planting_date', sa.Date(), nullable=False),
    sa.Column('planting_method', sa.Enum('direct_sow', 'transplant', name='plantingmethod'), nullable=False),
    sa.Column('plant_count', sa.Integer(), nullable=True),
    sa.Column('location_in_garden', sa.String(length=200), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['garden_id'], ['gardens.id'], ),
    sa.ForeignKeyConstraint(['germination_event_id'], ['germination_events.id'], ),
    sa.ForeignKeyConstraint(['plant_variety_id'], ['plant_varieties.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_planting_events_id'), 'planting_events', ['id'], unique=False)
    op.create_index(op.f('ix_planting_events_planting_date'), 'planting_events', ['planting_date'], unique=False)
    op.create_table('care_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('planting_event_id', sa.Integer(), nullable=True),
    sa.Column('task_type', sa.Enum('water', 'fertilize', 'prune', 'mulch', 'weed', 'pest_control', 'harvest', 'other', name='tasktype'), nullable=False),
    sa.Column('task_source', sa.Enum('auto_generated', 'manual', name='tasksource'), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'completed', 'skipped', name='taskstatus'), nullable=False),
    sa.Column('completed_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['planting_event_id'], ['planting_events.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_care_tasks_due_date'), 'care_tasks', ['due_date'], unique=False)
    op.create_index(op.f('ix_care_tasks_id'), 'care_tasks', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_care_tasks_id'), table_name='care_tasks')
    op.drop_index(op.f('ix_care_tasks_due_date'), table_name='care_tasks')
    op.drop_table('care_tasks')
    op.drop_index(op.f('ix_planting_events_planting_date'), table_name='planting_events')
    op.drop_index(op.f('ix_planting_events_id'), table_name='planting_events')
    op.drop_table('planting_events')
    op.drop_index(op.f('ix_germination_events_id'), table_name='germination_events')
    op.drop_table('germination_events')
    op.drop_index(op.f('ix_seed_batches_id'), table_name='seed_batches')
    op.drop_table('seed_batches')
    op.drop_index(op.f('ix_gardens_id'), table_name='gardens')
    op.drop_table('gardens')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_plant_varieties_id'), table_name='plant_varieties')
    op.drop_index(op.f('ix_plant_varieties_common_name'), table_name='plant_varieties')
    op.drop_table('plant_varieties')

    # Drop ENUM types (PostgreSQL specific)
    op.execute('DROP TYPE IF EXISTS taskstatus')
    op.execute('DROP TYPE IF EXISTS tasksource')
    op.execute('DROP TYPE IF EXISTS tasktype')
    op.execute('DROP TYPE IF EXISTS plantingmethod')
    op.execute('DROP TYPE IF EXISTS waterrequirement')
    op.execute('DROP TYPE IF EXISTS sunrequirement')
    # ### end Alembic commands ###
