"""CareTask model - unified task model"""
from sqlalchemy import Column, Integer, String, DateTime, ForeignKey, Date, Boolean, Text, Enum as SQLEnum
from sqlalchemy.orm import relationship
from sqlalchemy.sql import func
from app.database import Base
import enum


class TaskType(str, enum.Enum):
    """Types of care tasks"""
    WATER = "water"
    FERTILIZE = "fertilize"
    PRUNE = "prune"
    MULCH = "mulch"
    WEED = "weed"
    PEST_CONTROL = "pest_control"
    HARVEST = "harvest"
    OTHER = "other"


class TaskStatus(str, enum.Enum):
    """Task completion status"""
    PENDING = "pending"
    COMPLETED = "completed"
    SKIPPED = "skipped"


class TaskSource(str, enum.Enum):
    """How the task was created"""
    AUTO_GENERATED = "auto_generated"  # Created by rules engine
    MANUAL = "manual"                   # Created by user


class TaskPriority(str, enum.Enum):
    """Task priority levels"""
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"


class RecurrenceFrequency(str, enum.Enum):
    """Task recurrence frequency"""
    DAILY = "daily"
    WEEKLY = "weekly"
    BIWEEKLY = "biweekly"
    MONTHLY = "monthly"


class CareTask(Base):
    """
    Unified task model for all gardening activities.
    Can be auto-generated by rules or manually created by users.
    Supports priorities and recurring tasks.
    """
    __tablename__ = "care_tasks"

    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(Integer, ForeignKey("users.id"), nullable=False)
    planting_event_id = Column(Integer, ForeignKey("planting_events.id"), nullable=True)

    # Task details
    task_type = Column(SQLEnum(TaskType), nullable=False)
    task_source = Column(SQLEnum(TaskSource), nullable=False, default=TaskSource.MANUAL)
    title = Column(String(200), nullable=False)
    description = Column(Text, nullable=True)

    # Priority (NEW)
    priority = Column(SQLEnum(TaskPriority), nullable=False, default=TaskPriority.MEDIUM)

    # Scheduling
    due_date = Column(Date, nullable=False, index=True)

    # Recurring tasks (NEW)
    is_recurring = Column(Boolean, nullable=False, default=False)
    recurrence_frequency = Column(SQLEnum(RecurrenceFrequency), nullable=True)
    parent_task_id = Column(Integer, ForeignKey("care_tasks.id"), nullable=True)

    # Completion tracking
    status = Column(SQLEnum(TaskStatus), nullable=False, default=TaskStatus.PENDING)
    completed_date = Column(Date, nullable=True)

    notes = Column(Text, nullable=True)
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), onupdate=func.now())

    # Relationships
    user = relationship("User", back_populates="care_tasks")
    planting_event = relationship("PlantingEvent", back_populates="care_tasks")

    # Self-referential relationship for recurring tasks
    parent_task = relationship("CareTask", remote_side=[id], backref="child_tasks")
